import {
  KeyConfig,
  PresetDefinition,
  TopBarConfig,
  FullKeyboardConfig,
} from "@/types/keyboard";

export const ALL_KEYS: Record<string, KeyConfig> = {
  escape: {
    id: "escape",
    label: "Esc",
    value: "\x1b",
    category: "modifier",
    description: "Escape key",
  },
  tab: {
    id: "tab",
    label: "Tab",
    value: "\t",
    category: "modifier",
    description: "Tab key",
  },
  ctrl: {
    id: "ctrl",
    label: "Ctrl",
    value: "",
    category: "modifier",
    isModifier: true,
    description: "Control modifier (toggle)",
  },
  alt: {
    id: "alt",
    label: "Alt",
    value: "",
    category: "modifier",
    isModifier: true,
    description: "Alt modifier (toggle)",
  },
  shift: {
    id: "shift",
    label: "Shift",
    value: "",
    category: "modifier",
    isModifier: true,
    description: "Shift modifier (toggle)",
  },

  arrowUp: {
    id: "arrowUp",
    label: "↑",
    value: "\x1b[A",
    category: "arrow",
    description: "Up arrow",
  },
  arrowDown: {
    id: "arrowDown",
    label: "↓",
    value: "\x1b[B",
    category: "arrow",
    description: "Down arrow",
  },
  arrowLeft: {
    id: "arrowLeft",
    label: "←",
    value: "\x1b[D",
    category: "arrow",
    description: "Left arrow",
  },
  arrowRight: {
    id: "arrowRight",
    label: "→",
    value: "\x1b[C",
    category: "arrow",
    description: "Right arrow",
  },

  home: {
    id: "home",
    label: "Home",
    value: "\x1b[H",
    category: "navigation",
    description: "Home key",
  },
  end: {
    id: "end",
    label: "End",
    value: "\x1b[F",
    category: "navigation",
    description: "End key",
  },
  pageUp: {
    id: "pageUp",
    label: "PgUp",
    value: "\x1b[5~",
    category: "navigation",
    description: "Page Up",
  },
  pageDown: {
    id: "pageDown",
    label: "PgDn",
    value: "\x1b[6~",
    category: "navigation",
    description: "Page Down",
  },
  insert: {
    id: "insert",
    label: "Ins",
    value: "\x1b[2~",
    category: "navigation",
    description: "Insert key",
  },
  delete: {
    id: "delete",
    label: "Del",
    value: "\x1b[3~",
    category: "navigation",
    description: "Delete key",
  },

  f1: { id: "f1", label: "F1", value: "\x1bOP", category: "function" },
  f2: { id: "f2", label: "F2", value: "\x1bOQ", category: "function" },
  f3: { id: "f3", label: "F3", value: "\x1bOR", category: "function" },
  f4: { id: "f4", label: "F4", value: "\x1bOS", category: "function" },
  f5: { id: "f5", label: "F5", value: "\x1b[15~", category: "function" },
  f6: { id: "f6", label: "F6", value: "\x1b[17~", category: "function" },
  f7: { id: "f7", label: "F7", value: "\x1b[18~", category: "function" },
  f8: { id: "f8", label: "F8", value: "\x1b[19~", category: "function" },
  f9: { id: "f9", label: "F9", value: "\x1b[20~", category: "function" },
  f10: { id: "f10", label: "F10", value: "\x1b[21~", category: "function" },
  f11: { id: "f11", label: "F11", value: "\x1b[23~", category: "function" },
  f12: { id: "f12", label: "F12", value: "\x1b[24~", category: "function" },

  num0: {
    id: "num0",
    label: "0",
    value: "0",
    category: "number",
    width: "narrow",
  },
  num1: {
    id: "num1",
    label: "1",
    value: "1",
    category: "number",
    width: "narrow",
  },
  num2: {
    id: "num2",
    label: "2",
    value: "2",
    category: "number",
    width: "narrow",
  },
  num3: {
    id: "num3",
    label: "3",
    value: "3",
    category: "number",
    width: "narrow",
  },
  num4: {
    id: "num4",
    label: "4",
    value: "4",
    category: "number",
    width: "narrow",
  },
  num5: {
    id: "num5",
    label: "5",
    value: "5",
    category: "number",
    width: "narrow",
  },
  num6: {
    id: "num6",
    label: "6",
    value: "6",
    category: "number",
    width: "narrow",
  },
  num7: {
    id: "num7",
    label: "7",
    value: "7",
    category: "number",
    width: "narrow",
  },
  num8: {
    id: "num8",
    label: "8",
    value: "8",
    category: "number",
    width: "narrow",
  },
  num9: {
    id: "num9",
    label: "9",
    value: "9",
    category: "number",
    width: "narrow",
  },

  tilde: { id: "tilde", label: "~", value: "~", category: "symbol" },
  backtick: { id: "backtick", label: "`", value: "`", category: "symbol" },
  exclamation: {
    id: "exclamation",
    label: "!",
    value: "!",
    category: "symbol",
  },
  at: { id: "at", label: "@", value: "@", category: "symbol" },
  hash: { id: "hash", label: "#", value: "#", category: "symbol" },
  dollar: { id: "dollar", label: "$", value: "$", category: "symbol" },
  percent: { id: "percent", label: "%", value: "%", category: "symbol" },
  caret: { id: "caret", label: "^", value: "^", category: "symbol" },
  ampersand: { id: "ampersand", label: "&", value: "&", category: "symbol" },
  asterisk: { id: "asterisk", label: "*", value: "*", category: "symbol" },

  minus: { id: "minus", label: "-", value: "-", category: "operator" },
  underscore: {
    id: "underscore",
    label: "_",
    value: "_",
    category: "operator",
  },
  equals: { id: "equals", label: "=", value: "=", category: "operator" },
  plus: { id: "plus", label: "+", value: "+", category: "operator" },
  pipe: { id: "pipe", label: "|", value: "|", category: "operator" },
  backslash: {
    id: "backslash",
    label: "\\",
    value: "\\",
    category: "operator",
  },
  slash: { id: "slash", label: "/", value: "/", category: "operator" },
  question: { id: "question", label: "?", value: "?", category: "operator" },

  parenLeft: {
    id: "parenLeft",
    label: "(",
    value: "(",
    category: "punctuation",
  },
  parenRight: {
    id: "parenRight",
    label: ")",
    value: ")",
    category: "punctuation",
  },
  bracketLeft: {
    id: "bracketLeft",
    label: "[",
    value: "[",
    category: "punctuation",
  },
  bracketRight: {
    id: "bracketRight",
    label: "]",
    value: "]",
    category: "punctuation",
  },
  braceLeft: {
    id: "braceLeft",
    label: "{",
    value: "{",
    category: "punctuation",
  },
  braceRight: {
    id: "braceRight",
    label: "}",
    value: "}",
    category: "punctuation",
  },
  angleBracketLeft: {
    id: "angleBracketLeft",
    label: "<",
    value: "<",
    category: "punctuation",
  },
  angleBracketRight: {
    id: "angleBracketRight",
    label: ">",
    value: ">",
    category: "punctuation",
  },

  semicolon: {
    id: "semicolon",
    label: ";",
    value: ";",
    category: "punctuation",
  },
  colon: { id: "colon", label: ":", value: ":", category: "punctuation" },
  singleQuote: {
    id: "singleQuote",
    label: "'",
    value: "'",
    category: "punctuation",
  },
  doubleQuote: {
    id: "doubleQuote",
    label: '"',
    value: '"',
    category: "punctuation",
  },
  comma: { id: "comma", label: ",", value: ",", category: "punctuation" },
  period: { id: "period", label: ".", value: ".", category: "punctuation" },

  enter: {
    id: "enter",
    label: "Enter",
    value: "\r",
    category: "action",
    width: "wide",
    description: "Enter/Return",
  },
  space: {
    id: "space",
    label: "Space",
    value: " ",
    category: "action",
    width: "wide",
    description: "Space bar",
  },
  backspace: {
    id: "backspace",
    label: "Bksp",
    value: "\x08",
    category: "action",
    description: "Backspace",
  },
  clear: {
    id: "clear",
    label: "Clear",
    value: "\x0c",
    category: "action",
    description: "Clear screen",
  },

  ctrlC: {
    id: "ctrlC",
    label: "^C",
    value: "\x03",
    category: "shortcut",
    description: "Ctrl+C (interrupt)",
  },
  ctrlD: {
    id: "ctrlD",
    label: "^D",
    value: "\x04",
    category: "shortcut",
    description: "Ctrl+D (EOF)",
  },
  ctrlZ: {
    id: "ctrlZ",
    label: "^Z",
    value: "\x1a",
    category: "shortcut",
    description: "Ctrl+Z (suspend)",
  },
  ctrlL: {
    id: "ctrlL",
    label: "^L",
    value: "\x0c",
    category: "shortcut",
    description: "Ctrl+L (clear)",
  },
  ctrlA: {
    id: "ctrlA",
    label: "^A",
    value: "\x01",
    category: "shortcut",
    description: "Ctrl+A (line start)",
  },
  ctrlE: {
    id: "ctrlE",
    label: "^E",
    value: "\x05",
    category: "shortcut",
    description: "Ctrl+E (line end)",
  },
  ctrlK: {
    id: "ctrlK",
    label: "^K",
    value: "\x0b",
    category: "shortcut",
    description: "Ctrl+K (kill line)",
  },
  ctrlU: {
    id: "ctrlU",
    label: "^U",
    value: "\x15",
    category: "shortcut",
    description: "Ctrl+U (kill to start)",
  },
  ctrlW: {
    id: "ctrlW",
    label: "^W",
    value: "\x17",
    category: "shortcut",
    description: "Ctrl+W (kill word)",
  },
  ctrlR: {
    id: "ctrlR",
    label: "^R",
    value: "\x12",
    category: "shortcut",
    description: "Ctrl+R (reverse search)",
  },
  ctrlY: {
    id: "ctrlY",
    label: "^Y",
    value: "\x19",
    category: "shortcut",
    description: "Ctrl+Y (yank)",
  },
  ctrlT: {
    id: "ctrlT",
    label: "^T",
    value: "\x14",
    category: "shortcut",
    description: "Ctrl+T (transpose)",
  },
  ctrlN: {
    id: "ctrlN",
    label: "^N",
    value: "\x0e",
    category: "shortcut",
    description: "Ctrl+N (next history)",
  },
  ctrlP: {
    id: "ctrlP",
    label: "^P",
    value: "\x10",
    category: "shortcut",
    description: "Ctrl+P (prev history)",
  },
  ctrlB: {
    id: "ctrlB",
    label: "^B",
    value: "\x02",
    category: "shortcut",
    description: "Ctrl+B (back char)",
  },
  ctrlF: {
    id: "ctrlF",
    label: "^F",
    value: "\x06",
    category: "shortcut",
    description: "Ctrl+F (forward char)",
  },

  altF: {
    id: "altF",
    label: "Alt+F",
    value: "\x1bf",
    category: "shortcut",
    description: "Alt+F (forward word)",
  },
  altB: {
    id: "altB",
    label: "Alt+B",
    value: "\x1bb",
    category: "shortcut",
    description: "Alt+B (back word)",
  },
  altD: {
    id: "altD",
    label: "Alt+D",
    value: "\x1bd",
    category: "shortcut",
    description: "Alt+D (delete word)",
  },
  shiftTab: {
    id: "shiftTab",
    label: "Shift+Tab",
    value: "\x1b[Z",
    category: "shortcut",
    description: "Shift+Tab (reverse tab)",
  },

  paste: {
    id: "paste",
    label: "Paste",
    value: "PASTE",
    category: "action",
    description: "Paste clipboard",
  },
  history: {
    id: "history",
    label: "Hist",
    value: "\x1b[A",
    category: "action",
    description: "Command history (up arrow)",
  },
  complete: {
    id: "complete",
    label: "Comp",
    value: "\t",
    category: "action",
    description: "Tab completion",
  },
};

const defaultTopBar: TopBarConfig = {
  pinnedKeys: [],
  keys: [
    ALL_KEYS.escape,
    ALL_KEYS.tab,
    ALL_KEYS.ctrl,
    ALL_KEYS.alt,
    ALL_KEYS.shift,
    ALL_KEYS.arrowUp,
    ALL_KEYS.arrowDown,
    ALL_KEYS.arrowLeft,
    ALL_KEYS.arrowRight,
    ALL_KEYS.backslash,
    ALL_KEYS.pipe,
    ALL_KEYS.tilde,
    ALL_KEYS.minus,
  ],
};

const defaultFullKeyboard: FullKeyboardConfig = {
  rows: [
    {
      id: "function-keys",
      category: "function",
      label: "Function Keys",
      visible: true,
      keys: [
        ALL_KEYS.f1,
        ALL_KEYS.f2,
        ALL_KEYS.f3,
        ALL_KEYS.f4,
        ALL_KEYS.f5,
        ALL_KEYS.f6,
        ALL_KEYS.f7,
        ALL_KEYS.f8,
        ALL_KEYS.f9,
        ALL_KEYS.f10,
        ALL_KEYS.f11,
        ALL_KEYS.f12,
      ],
    },
    {
      id: "navigation",
      category: "navigation",
      label: "Navigation",
      visible: true,
      keys: [
        ALL_KEYS.insert,
        ALL_KEYS.home,
        ALL_KEYS.pageUp,
        ALL_KEYS.delete,
        ALL_KEYS.end,
        ALL_KEYS.pageDown,
      ],
    },
    {
      id: "quick-actions",
      category: "action",
      label: "Quick Actions",
      visible: true,
      keys: [
        ALL_KEYS.paste,
        ALL_KEYS.clear,
        ALL_KEYS.history,
        ALL_KEYS.complete,
      ],
    },
    {
      id: "numbers",
      category: "number",
      label: "Numbers",
      visible: true,
      keys: [
        ALL_KEYS.num1,
        ALL_KEYS.num2,
        ALL_KEYS.num3,
        ALL_KEYS.num4,
        ALL_KEYS.num5,
        ALL_KEYS.num6,
        ALL_KEYS.num7,
        ALL_KEYS.num8,
        ALL_KEYS.num9,
        ALL_KEYS.num0,
      ],
    },
    {
      id: "symbols-1",
      category: "symbol",
      label: "Symbols",
      visible: true,
      keys: [
        ALL_KEYS.backtick,
        ALL_KEYS.tilde,
        ALL_KEYS.exclamation,
        ALL_KEYS.at,
        ALL_KEYS.hash,
        ALL_KEYS.dollar,
        ALL_KEYS.percent,
        ALL_KEYS.caret,
        ALL_KEYS.ampersand,
        ALL_KEYS.asterisk,
        ALL_KEYS.parenLeft,
        ALL_KEYS.parenRight,
      ],
    },
    {
      id: "operators",
      category: "operator",
      label: "Operators",
      visible: true,
      keys: [
        ALL_KEYS.minus,
        ALL_KEYS.underscore,
        ALL_KEYS.equals,
        ALL_KEYS.plus,
        ALL_KEYS.bracketLeft,
        ALL_KEYS.braceLeft,
        ALL_KEYS.bracketRight,
        ALL_KEYS.braceRight,
        ALL_KEYS.backslash,
        ALL_KEYS.pipe,
        ALL_KEYS.semicolon,
        ALL_KEYS.colon,
      ],
    },
    {
      id: "punctuation",
      category: "punctuation",
      label: "Punctuation",
      visible: true,
      keys: [
        ALL_KEYS.singleQuote,
        ALL_KEYS.doubleQuote,
        ALL_KEYS.comma,
        ALL_KEYS.angleBracketLeft,
        ALL_KEYS.period,
        ALL_KEYS.angleBracketRight,
        ALL_KEYS.slash,
        ALL_KEYS.question,
      ],
    },
    {
      id: "basic-actions",
      category: "action",
      label: "Basic Actions",
      visible: true,
      keys: [ALL_KEYS.enter, ALL_KEYS.space, ALL_KEYS.backspace],
    },
    {
      id: "ctrl-shortcuts",
      category: "shortcut",
      label: "Ctrl Shortcuts",
      visible: true,
      keys: [
        ALL_KEYS.ctrlC,
        ALL_KEYS.ctrlD,
        ALL_KEYS.ctrlZ,
        ALL_KEYS.ctrlL,
        ALL_KEYS.ctrlA,
        ALL_KEYS.ctrlE,
        ALL_KEYS.ctrlK,
        ALL_KEYS.ctrlU,
        ALL_KEYS.ctrlW,
        ALL_KEYS.ctrlR,
        ALL_KEYS.ctrlY,
        ALL_KEYS.altF,
        ALL_KEYS.shiftTab,
      ],
    },
  ],
};

const minimalTopBar: TopBarConfig = {
  pinnedKeys: [],
  keys: [
    ALL_KEYS.escape,
    ALL_KEYS.tab,
    ALL_KEYS.ctrl,
    ALL_KEYS.alt,
    ALL_KEYS.shift,
    ALL_KEYS.arrowUp,
    ALL_KEYS.arrowDown,
    ALL_KEYS.arrowLeft,
    ALL_KEYS.arrowRight,
    ALL_KEYS.tilde,
    ALL_KEYS.pipe,
    ALL_KEYS.slash,
  ],
};

const minimalFullKeyboard: FullKeyboardConfig = {
  rows: [
    {
      id: "navigation",
      category: "navigation",
      label: "Navigation",
      visible: true,
      keys: [ALL_KEYS.home, ALL_KEYS.end, ALL_KEYS.pageUp, ALL_KEYS.pageDown],
    },
    {
      id: "essential-symbols",
      category: "symbol",
      label: "Essential Symbols",
      visible: true,
      keys: [
        ALL_KEYS.tilde,
        ALL_KEYS.backtick,
        ALL_KEYS.pipe,
        ALL_KEYS.backslash,
        ALL_KEYS.slash,
        ALL_KEYS.minus,
        ALL_KEYS.underscore,
        ALL_KEYS.dollar,
      ],
    },
    {
      id: "basic-actions",
      category: "action",
      label: "Actions",
      visible: true,
      keys: [
        ALL_KEYS.paste,
        ALL_KEYS.enter,
        ALL_KEYS.space,
        ALL_KEYS.backspace,
      ],
    },
    {
      id: "essential-shortcuts",
      category: "shortcut",
      label: "Shortcuts",
      visible: true,
      keys: [
        ALL_KEYS.ctrlC,
        ALL_KEYS.ctrlD,
        ALL_KEYS.ctrlL,
        ALL_KEYS.ctrlZ,
        ALL_KEYS.shiftTab,
      ],
    },
  ],
};
const developerTopBar: TopBarConfig = {
  pinnedKeys: [],
  keys: [
    ALL_KEYS.escape,
    ALL_KEYS.tab,
    ALL_KEYS.ctrl,
    ALL_KEYS.alt,
    ALL_KEYS.shift,
    ALL_KEYS.arrowUp,
    ALL_KEYS.arrowDown,
    ALL_KEYS.arrowLeft,
    ALL_KEYS.arrowRight,
    ALL_KEYS.bracketLeft,
    ALL_KEYS.bracketRight,
    ALL_KEYS.braceLeft,
    ALL_KEYS.braceRight,
    ALL_KEYS.pipe,
    ALL_KEYS.backslash,
  ],
};

const developerFullKeyboard: FullKeyboardConfig = {
  rows: [
    {
      id: "brackets",
      category: "punctuation",
      label: "Brackets",
      visible: true,
      keys: [
        ALL_KEYS.parenLeft,
        ALL_KEYS.parenRight,
        ALL_KEYS.bracketLeft,
        ALL_KEYS.bracketRight,
        ALL_KEYS.braceLeft,
        ALL_KEYS.braceRight,
        ALL_KEYS.angleBracketLeft,
        ALL_KEYS.angleBracketRight,
      ],
    },
    {
      id: "coding-symbols",
      category: "symbol",
      label: "Coding Symbols",
      visible: true,
      keys: [
        ALL_KEYS.backtick,
        ALL_KEYS.tilde,
        ALL_KEYS.exclamation,
        ALL_KEYS.at,
        ALL_KEYS.hash,
        ALL_KEYS.dollar,
        ALL_KEYS.percent,
        ALL_KEYS.caret,
        ALL_KEYS.ampersand,
        ALL_KEYS.asterisk,
      ],
    },
    {
      id: "operators",
      category: "operator",
      label: "Operators",
      visible: true,
      keys: [
        ALL_KEYS.equals,
        ALL_KEYS.plus,
        ALL_KEYS.minus,
        ALL_KEYS.underscore,
        ALL_KEYS.pipe,
        ALL_KEYS.backslash,
        ALL_KEYS.slash,
        ALL_KEYS.question,
        ALL_KEYS.semicolon,
        ALL_KEYS.colon,
      ],
    },
    {
      id: "quotes",
      category: "punctuation",
      label: "Quotes",
      visible: true,
      keys: [
        ALL_KEYS.singleQuote,
        ALL_KEYS.doubleQuote,
        ALL_KEYS.comma,
        ALL_KEYS.period,
      ],
    },
    {
      id: "navigation",
      category: "navigation",
      label: "Navigation",
      visible: true,
      keys: [ALL_KEYS.home, ALL_KEYS.end, ALL_KEYS.pageUp, ALL_KEYS.pageDown],
    },
    {
      id: "actions",
      category: "action",
      label: "Actions",
      visible: true,
      keys: [
        ALL_KEYS.paste,
        ALL_KEYS.enter,
        ALL_KEYS.space,
        ALL_KEYS.backspace,
      ],
    },
    {
      id: "dev-shortcuts",
      category: "shortcut",
      label: "Dev Shortcuts",
      visible: true,
      keys: [
        ALL_KEYS.ctrlC,
        ALL_KEYS.ctrlZ,
        ALL_KEYS.ctrlA,
        ALL_KEYS.ctrlE,
        ALL_KEYS.ctrlK,
        ALL_KEYS.ctrlU,
        ALL_KEYS.ctrlR,
        ALL_KEYS.ctrlW,
        ALL_KEYS.shiftTab,
      ],
    },
  ],
};

const sysadminTopBar: TopBarConfig = {
  pinnedKeys: [],
  keys: [
    ALL_KEYS.escape,
    ALL_KEYS.tab,
    ALL_KEYS.ctrl,
    ALL_KEYS.alt,
    ALL_KEYS.shift,
    ALL_KEYS.arrowUp,
    ALL_KEYS.arrowDown,
    ALL_KEYS.arrowLeft,
    ALL_KEYS.arrowRight,
    ALL_KEYS.home,
    ALL_KEYS.end,
    ALL_KEYS.pipe,
    ALL_KEYS.slash,
  ],
};

const sysadminFullKeyboard: FullKeyboardConfig = {
  rows: [
    {
      id: "function-keys",
      category: "function",
      label: "Function Keys",
      visible: true,
      keys: [
        ALL_KEYS.f1,
        ALL_KEYS.f2,
        ALL_KEYS.f3,
        ALL_KEYS.f4,
        ALL_KEYS.f5,
        ALL_KEYS.f6,
        ALL_KEYS.f7,
        ALL_KEYS.f8,
        ALL_KEYS.f9,
        ALL_KEYS.f10,
        ALL_KEYS.f11,
        ALL_KEYS.f12,
      ],
    },
    {
      id: "navigation",
      category: "navigation",
      label: "Navigation",
      visible: true,
      keys: [
        ALL_KEYS.insert,
        ALL_KEYS.home,
        ALL_KEYS.pageUp,
        ALL_KEYS.delete,
        ALL_KEYS.end,
        ALL_KEYS.pageDown,
      ],
    },
    {
      id: "admin-symbols",
      category: "symbol",
      label: "Admin Symbols",
      visible: true,
      keys: [
        ALL_KEYS.tilde,
        ALL_KEYS.slash,
        ALL_KEYS.pipe,
        ALL_KEYS.backslash,
        ALL_KEYS.dollar,
        ALL_KEYS.hash,
        ALL_KEYS.minus,
        ALL_KEYS.underscore,
      ],
    },
    {
      id: "actions",
      category: "action",
      label: "Actions",
      visible: true,
      keys: [
        ALL_KEYS.paste,
        ALL_KEYS.clear,
        ALL_KEYS.history,
        ALL_KEYS.complete,
      ],
    },
    {
      id: "system-shortcuts",
      category: "shortcut",
      label: "System Shortcuts",
      visible: true,
      keys: [
        ALL_KEYS.ctrlC,
        ALL_KEYS.ctrlD,
        ALL_KEYS.ctrlZ,
        ALL_KEYS.ctrlL,
        ALL_KEYS.ctrlR,
        ALL_KEYS.ctrlU,
        ALL_KEYS.shiftTab,
      ],
    },
  ],
};

const compactTopBar: TopBarConfig = {
  pinnedKeys: [],
  keys: [
    ALL_KEYS.escape,
    ALL_KEYS.tab,
    ALL_KEYS.ctrl,
    ALL_KEYS.alt,
    ALL_KEYS.shift,
    ALL_KEYS.arrowUp,
    ALL_KEYS.arrowDown,
    ALL_KEYS.arrowLeft,
    ALL_KEYS.arrowRight,
    ALL_KEYS.home,
    ALL_KEYS.end,
    ALL_KEYS.pipe,
    ALL_KEYS.tilde,
    ALL_KEYS.slash,
    ALL_KEYS.minus,
  ],
};

const compactFullKeyboard: FullKeyboardConfig = {
  rows: [
    {
      id: "function-keys",
      category: "function",
      label: "F-Keys",
      visible: true,
      keys: [
        ALL_KEYS.f1,
        ALL_KEYS.f2,
        ALL_KEYS.f3,
        ALL_KEYS.f4,
        ALL_KEYS.f5,
        ALL_KEYS.f6,
        ALL_KEYS.f7,
        ALL_KEYS.f8,
        ALL_KEYS.f9,
        ALL_KEYS.f10,
        ALL_KEYS.f11,
        ALL_KEYS.f12,
      ],
    },
    {
      id: "nav-nums",
      category: "navigation",
      label: "Nav + Numbers",
      visible: true,
      keys: [
        ALL_KEYS.pageUp,
        ALL_KEYS.pageDown,
        ALL_KEYS.num1,
        ALL_KEYS.num2,
        ALL_KEYS.num3,
        ALL_KEYS.num4,
        ALL_KEYS.num5,
        ALL_KEYS.num6,
        ALL_KEYS.num7,
        ALL_KEYS.num8,
        ALL_KEYS.num9,
        ALL_KEYS.num0,
      ],
    },
    {
      id: "all-symbols",
      category: "symbol",
      label: "Symbols",
      visible: true,
      keys: [
        ALL_KEYS.backtick,
        ALL_KEYS.tilde,
        ALL_KEYS.exclamation,
        ALL_KEYS.at,
        ALL_KEYS.hash,
        ALL_KEYS.dollar,
        ALL_KEYS.percent,
        ALL_KEYS.caret,
        ALL_KEYS.ampersand,
        ALL_KEYS.asterisk,
        ALL_KEYS.minus,
        ALL_KEYS.underscore,
        ALL_KEYS.equals,
        ALL_KEYS.plus,
      ],
    },
    {
      id: "brackets-ops",
      category: "operator",
      label: "Brackets + Ops",
      visible: true,
      keys: [
        ALL_KEYS.parenLeft,
        ALL_KEYS.parenRight,
        ALL_KEYS.bracketLeft,
        ALL_KEYS.bracketRight,
        ALL_KEYS.braceLeft,
        ALL_KEYS.braceRight,
        ALL_KEYS.angleBracketLeft,
        ALL_KEYS.angleBracketRight,
        ALL_KEYS.pipe,
        ALL_KEYS.backslash,
        ALL_KEYS.slash,
        ALL_KEYS.question,
      ],
    },
    {
      id: "punct-actions",
      category: "punctuation",
      label: "Punct + Actions",
      visible: true,
      keys: [
        ALL_KEYS.singleQuote,
        ALL_KEYS.doubleQuote,
        ALL_KEYS.semicolon,
        ALL_KEYS.colon,
        ALL_KEYS.comma,
        ALL_KEYS.period,
        ALL_KEYS.paste,
        ALL_KEYS.clear,
      ],
    },
    {
      id: "shortcuts",
      category: "shortcut",
      label: "Shortcuts",
      visible: true,
      keys: [
        ALL_KEYS.ctrlC,
        ALL_KEYS.ctrlD,
        ALL_KEYS.ctrlZ,
        ALL_KEYS.ctrlL,
        ALL_KEYS.ctrlA,
        ALL_KEYS.ctrlE,
        ALL_KEYS.ctrlK,
        ALL_KEYS.ctrlU,
        ALL_KEYS.ctrlW,
        ALL_KEYS.ctrlR,
        ALL_KEYS.shiftTab,
      ],
    },
  ],
};

export const PRESET_DEFINITIONS: PresetDefinition[] = [
  {
    id: "default",
    name: "Default",
    description: "Full-featured keyboard with all keys organized by category",
    topBar: defaultTopBar,
    fullKeyboard: defaultFullKeyboard,
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Just the essentials for basic terminal usage",
    topBar: minimalTopBar,
    fullKeyboard: minimalFullKeyboard,
  },
  {
    id: "developer",
    name: "Developer",
    description:
      "Optimized for coding with easy access to symbols and brackets",
    topBar: developerTopBar,
    fullKeyboard: developerFullKeyboard,
  },
  {
    id: "sysadmin",
    name: "System Admin",
    description: "Function keys and navigation for system administration",
    topBar: sysadminTopBar,
    fullKeyboard: sysadminFullKeyboard,
  },
  {
    id: "compact",
    name: "Compact",
    description: "More keys per row with tighter spacing for larger screens",
    topBar: compactTopBar,
    fullKeyboard: compactFullKeyboard,
  },
];

export function getPresetById(id: string): PresetDefinition | undefined {
  return PRESET_DEFINITIONS.find((preset) => preset.id === id);
}

export function getKeysByCategory(category: string): KeyConfig[] {
  return Object.values(ALL_KEYS).filter((key) => key.category === category);
}

export function getKeyById(id: string): KeyConfig | undefined {
  return ALL_KEYS[id];
}
